---
# .terraform-docs.yml
formatter: markdown table

header-from: main.tf
footer-from: ""

sections:
#  show: all
  hide: []

content: |-
    {{ .Header }}

    <!--
    ``hcl
    { include "examples/main.tf" }}
    ```
    -->

    {{ .Requirements }}

    {{ .Providers }}

    {{ .Inputs }}

    {{ .Outputs }}

    {{ .Modules }}
    


    {{ .Resources }}

    {{ .Footer }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  html: true
  ident: 2
  required: true
  sensitive: true
  type: true
