npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  instantencore:
    npmAlwaysAuth: true
    npmAuthIdent: "${NPM_AUTH_IDENT_SWITCHCASE-fallback}"
    npmPublishRegistry: "https://pkgs.dev.azure.com/switchcasegroup/_packaging/SwitchCase/npm/registry/"
    npmRegistryServer: "https://pkgs.dev.azure.com/switchcasegroup/_packaging/SwitchCase/npm/registry/"
  switchcase:
    npmAlwaysAuth: true
    npmAuthIdent: "${NPM_AUTH_IDENT_SWITCHCASE-fallback}"
    npmPublishRegistry: "https://pkgs.dev.azure.com/switchcasegroup/_packaging/SwitchCase/npm/registry/"
    npmRegistryServer: "https://pkgs.dev.azure.com/switchcasegroup/_packaging/SwitchCase/npm/registry/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
